"use strict";
exports.__esModule = true;
var teacher_1 = require("./teacher");
var student_1 = require("./student");
var school_1 = require("./school");
console.log("________________");
var teacher1 = new teacher_1.Teacher("T1", 31);
var teacher2 = new teacher_1.Teacher("T2", 32);
var teacher3 = new teacher_1.Teacher("T3", 33);
var student1 = new student_1.Student("S1", 21);
var student2 = new student_1.Student("S1", 21);
var student3 = new student_1.Student("S1", 21);
var MySchool = new school_1.School();
MySchool.addTeachers(teacher1.toString());
MySchool.addTeachers(teacher2.toString());
MySchool.addTeachers(teacher3.toString());
